### ISSUE TITLE
關於之前提到的

### ISSUE THREAD

**Issue by sanalinn** [akira02/Zero-Memo#4]
<img width="1194" alt="screen shot 2017-07-24 at 7 46 37 pm" src="https://user-images.githubusercontent.com/20025967/28522264-ebfa2f5a-70a9-11e7-80ba-30d5465c0300.png">

雖然大概已經知道了()
較低解析度(?)狀態下dashboard背景會被切掉剩一半的狀態，經確認是osx下的chrome才會發生(的瀏覽器的bug)

**Comment by akira02** [comment]
不，這不是Bug，這是(Chrome的)feature(？
原因似乎是Chrome實在是太聰明了，會停止渲染沒有出現在視窗裡面的圖片，來節省記憶體的樣子

我會再找找看有沒有方法可以解決ww

**Comment by ray851107** [comment]
@sanalinn 加這個貌似有用
```css
._lch_, ._lc_ {
    overflow-x: initial !important;
}
```
不太確定會不會有其他副作用 QQ
